sonar.projectKey=sonar-node-app 
	sonar.projectName=Sonar Node App 
	sonar.projectVersion=1.0 
	sonar.sources=. 
	sonar.host.url=http://localhost:9000 
	sonar.login=squ_64d5496d3cf0b24dc17240ce6a7a71977f2bfb2b
